apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx
    purpose: helm
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 8080 #target-port
    nodePort: {{ .Values.service.nodePort }}